app1/urls.py
from django.urls import path
from app1.views import *
app_name='malli'

urlpatterns=[
    path('a1_first/',a1_first,name='a1_first'),

]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='ram'

urlpatterns=[
    path('a2_one/',a2_one,name='a2-one'),
]

project10/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2
urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def a1_first(request):
    return render(request,'a1_first.html')
    

app2/views.py
from django.shortcuts import render

# Create your views here.
def a2_one(request):
    return render(request,'a2_one.html')

templates/a1_first.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>a1_first html page</h1>
        <a href="{% url 'ram:a2_one' %}">go to a2_one html page</a>
    </center>
</body>
</html>

templates/a2_one.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>welcome to a2_one html page</h1>
        <a href="{% url 'malli:a1_first' %}">go to a1_first html page</a>
    </center>
</body>
</html>